### ISSUE TITLE
SDDM Config Not Set Right

### ISSUE THREAD

**Issue by tsimonq2** [calamares/calamares#1016]
Here's our `displaymanager.conf`:

```yaml
displaymanagers:
  - sddm

defaultDesktopEnvironment:
    desktopFile: "Lubuntu"

basicSetup: false
sysconfigSetup: false
```
On fresh boot however, here's our `sddm.conf`:
```
[Autologin]
User=simonq
Session=lxqt
```

(Well, at least mine from when I set my user.)

Session should be `Lubuntu`, not `lxqt`.

We're using Calamares 3.2.1.
