### ISSUE TITLE
Mkinitcpio does not run properly on Calamares on ArchLinux.

### ISSUE THREAD

**Issue by Hayao0819** [calamares/calamares#1313]
**Describe the bug**
This problem occurred on ArchLinux.
In the middle of the installation, mkinitcpio fails to find / boot / vmlinuz-linux.
This problem is probably caused by [this](https://www.archlinux.org/news/new-kernel-packages-and-mkinitcpio-hooks/).

**To Reproduce**
1. Create archlinux including calamares with archiso. (With linux kernel)
2. Set unpaskfs as follows.

```
unpack:
    -   source: "/run/archiso/bootmnt/alter/x86_64/airootfs.sfs"
        sourcefs: "squashfs"
        destination: ""
    -   source: "/run/archiso/bootmnt/alter/boot/x86_64/vmlinuz"
        sourcefs: "file"
        destination: "/boot/vmlinuz"
```

3. Start the installation.

**Screenshots and Logs**
[caalmares.log](https://github.com/calamares/calamares/files/4164291/caalmares.log)

![image](https://user-images.githubusercontent.com/32128205/73924404-ca901a00-490f-11ea-9f67-08f55a6a6561.png)

**Additional context**
Installation on ArchLinux uses [Manjaro's PKGBUILD](https://gitlab.manjaro.org/packages/extra/calamares).
