### ISSUE TITLE
Feature Request: Expand NetInstall Module to Support Package Arrays

### ISSUE THREAD

**Issue by salientos** [calamares/calamares#1326]
**Is your feature request related to a problem? Please describe.**

In its current state the netinstall module supports single line entries for packages which could be seen as a limitation given that 'most' package managers support being given an array of packages to install.

**Describe the solution you'd like**

Instead of the current method within netinstall.yaml, the packages section looks like this, for example:

**packages:
    - nvidia
    - nvidia-settings
    - nvidia-utils**

What would be very useful is to be able to give an array of packages instead:

**packages:
    - ("nvidia nvidia-settings nvidia-utils")**

There are occasions whereby I would like to install a package but also include support packages that accompany it, for example, if I install let's say Ardour, i would like to include in a 'one hit' scenario, some soft synths and plugins too.

**packages:
    - ("ardour a2jmidid cadence calf eq10q harvid helm lsp-plugins xjadeo zyn-fusion")**

Rather than have these items individually listed, an array makes much more sense since 'most' package managers support this natively anyway.

**Comment by abucodonosor** [comment]
@adriaandegroot 

No need to change the format of the config, is doing that already if you set
critical: true on the package group if I remember correctly. So probably just a new flag in addition.

This:

```
- name: "Some Packages"
  description: "Some Packages"
  selected: true
  critical: true
  packages:
      - pkg1
      - pkg2
      - pkg3
```

should end up in $some_package_manager --install-flag pkg1 pkg2 pkg3

**Comment by adriaandegroot** [comment]
@salientos The netinstall module does offer each item of a group as an individually-selectable item; in the config @abucodonosor describes with *critical: true* that ensures that there is just one call to the package manager to install the items from that group, but you can still individually toggle them. What you're asking for is a group that can't be expanded to toggle the individual packages -- or, similarly, a group that can't toggle the individual items in it.

**Comment by adriaandegroot** [comment]
![Screenshot_20200225_174449](https://user-images.githubusercontent.com/19431457/75267454-8dc09000-57f6-11ea-9735-d219a081116b.png)

This can be achieved through **hidden subgroups**. It's a bit obscure, but is documented in the `README.md` for that module (not in the regular documentation, though). The screenshot above comes from this config file:

```
- name: "NVidia"
  description: "NVidia drivers"
  hidden: false
  selected: true
  critical: true
  subgroups:
    - name: "bogus"
      description: "package list"
      hidden: true
      selected: true
      critical: true
      packages:
        - nvidia-drivers
        - nvidia-control-panel
        - nvidia-gamelive
- name: "Ardour"
  description: "Ardour"
  hidden: false
  selected: true
  critical: true
  subgroups:
    - name: "bogus"
      description: "package list"
      hidden: true
      selected: true
      critical: true
      packages:
        - ardour
        - ardour-plugins
        - ardour-drivers
```

**Comment by adriaandegroot** [comment]
What happens here is the subgroup isn't displayed, because it is *hidden*. Because all of the items under "Nvidia" are hidden, it doesn't expand. The subgroup is *selected*, which is an implementation detail so it follows the selected state of its parent. Since it's not displayed, the name and description don't really matter. By marking the subgroup *critical*, the packages listed are passed to the package manager as one call (see explanation of critical-packages by @abucodonosor above).

This setup means that I can select "NVidia" and/or "Ardour", and that installs a handfull of packages for each option -- but I can't turn off individual items.

I'm pretty sure that covers what you're asking for.

**Comment by salientos** [comment]
@adriaandegroot That is exactly what I wanted and now i see it, makes perfect sense. Thank you for pointing out these additional capabilities i wasn't previously aware of. Much appreciated!

One question though, is the indentation displayed above critical for this approach as i know Calamares is quite sensitive where this is concerned?

**Comment by kkofler** [comment]
1. The indentation is important. This is not a Calamares-specific thing, but a "feature" of the YAML format. Similarly to Python, they decided to use indentation instead of start/end markers for lists. This makes it less verbose than XML, which mirrors all start `<tag>`s into end `</tag>`s (at least the nonempty ones – empty ones can be abbreviated `<tag/>`). I personally like C-style braces/brackets (as used, e.g., in JSON) best, but Calamares has chosen the indentation-based YAML.
2. I think it should work that way as well, but I haven't tested it.

**Comment by salientos** [comment]
Thank you @kkofler if you don't mind i'm going to test this first before closing, is that ok?

**Comment by salientos** [comment]
Tested and works perfectly, thank you both! Calamares just keeps getting better and better :D

**Comment by adriaandegroot** [comment]
If you have a build of Calamares (not packages, but built-from-source) there is an executable called `test_conf` in the build directory. It's meant to test config-files, but you can also use it to at least check your `netinstall.yaml` for some correctness. Run it with a path to the groups file (here, `/tmp/netinstall.yaml` is my groups file containing what I posted above, only with various kinds of badness).

 - Accidental tab character
   ```
[adridg@beastie .../calamares/build]$ ./test_conf /tmp/netinstall.yaml 
WARNING:/tmp/netinstall.yaml
WARNING: YAML parser error yaml-cpp: error at line 26, column 1: illegal tab when looking for indentation
```
 - Accidental outdent by one space
   ```
[adridg@beastie .../calamares/build]$ ./test_conf /tmp/netinstall.yaml 
WARNING:/tmp/netinstall.yaml
WARNING: YAML parser error yaml-cpp: error at line 29, column 8: end of map not found
```

If things are ok, then `test_conf` will complain **anyway**, since it's meant to parse module-config files, not general YAML, but it complains like this:

```
[adridg@beastie .../calamares/build]$ ./test_conf /tmp/netinstall.yaml 
WARNING:/tmp/netinstall.yaml
WARNING: not-a-YAML-map (type=3)
```

This tells you that the YAML could be parsed correctly, and that it yielded a type=3 YAML object -- which is a sequence. That's the right thing for **this specific file** to be, so you're probably ok then. For misusing-a-tool to check netinstall YAML files that's about as good as it'll be right now.

Writing all this stuff here tells me the documentation can be improved, and also that a tiny test-tool for netinstall YAML files would be handy.

**Comment by salientos** [comment]
One quick question, is it possible to have multiple subgroups in this scenario but, with hidden and selected set to false on the subgroups?

```yaml
- name: "Office Applications"
  description: "Installs Officet Applications"
  hidden: false
  selected: false
  critical: false
  subgroups:
    - name: "Libre Office Fresh"
      description: "libreoffice-fresh packages"
      hidden: false
      selected: false
      critical: true
      packages:
        - libreoffice-fresh
        - libreoffice-fresh-$LOCALE
        - hunspell-$LOCALE
  subgroups:
    - name: "Libre Office Still"
      description: "libreoffice-still packages"
      hidden: false
      selected: false
      critical: true
      packages:
        - libreoffice-still
        - libreoffice-still-$LOCALE
        - hunspell-$LOCALE
```
If not, is it something that might be worth thinking about?

Thanks in advance.
