### ISSUE TITLE
Feature Request: NetInstall Items and Esoteric Package Names Sanitisation

### ISSUE THREAD

**Issue by salientos** [calamares/calamares#1369]
**Is your feature request related to a problem? Please describe.**

Currently, the way netinstall lists it's packages is verbatim which, whilst functional, does not look very nice if, for example, i have curated packages with -git extensions from my repo.

**Describe the solution you'd like**

What i would like to propose is a two step configuration availability within the netinstall yaml config files that allow for **Pretty Naming** a package to install and providing the **Actual Package Name** to install that is hidden from the end user. For example, let's say **Qogir GTK Theme** is what is listed but actually **qogir-gtk-theme-git** is going to be installed.

```yaml
- name: "Additional Themes"
  description: "Installs Additonal GTK Themes"
  critical: false
  hidden: false
  selected: false
  packages:
    - Qogir GTK Theme
    - package=qogir-gtk-theme-git
```
So the **- package=qogir-gtk-theme-git** part is hidden from the end user but the package pretty name is visible. I appreciate that this is non-trivial and would require some rather hefty refactoring in the backend, but, maybe something for the future?

**Comment by adriaandegroot** [comment]
While it is very verbose, the way to do this within the existing setup is with subgroups:

```
    - name: "Themes"
      description: "Themes"
      hidden: false
      selected: false
      critical: false
      subgroups:
        - name: "Quogit"
          description: "Quogir GTK Theme"
          selected: true
          subgroups:
           - name: "bogus1"
             hidden: true
             packages:
               - quogir-gtk-git
        - name: "Quogir"
          description: "Qhogit Qt Theme"
          subgroups:
           - name: "bogus2"
             hidden: true
             packages:
               - quogir-gtk-git
```

The subgroups called *bogus* are hidden, but their packages still count (or they should -- if not it's a bug, you can see the packages added to GlobalStorage from the debug window when you *next* out of the netinstall viewstep. This lets you assign a nice human-readable name to a package -- and has as additional feature that you can install multiple packages under one human-readable name.

(This probably should be PR'ed into the wiki as a documentation improvement)
