### ISSUE TITLE
preservefile job's global config JSON dump succeeds, but results in a job error

### ISSUE THREAD

**Issue by kadler15** [calamares/calamares#1521]
**Describe the bug**
The preservefiles module's special *from* key value `config` results in a job error on successful global config dump:

```
Not all of the configured files could be preserved.
```

Also, the description of special *from* key values in sample config file [preservefiles.conf](https://github.com/calamares/calamares/blob/v3.2.30/src/modules/preservefiles/preservefiles.conf#L34) is inaccurate:

```yaml
# Special values for the key *from* are:
# - *log*, for the complete log file (up to the moment the preservefiles
#   module is run),
# - *config*, for the Calamares configuration file
# - *globals*, for a JSON dump of the contents of global storage
```

Value `config` dumps global storage as JSON, while value `globals` is undefined and results in a noop.

**To Reproduce**
1. Use the following in `/etc/calamares/settings.conf`:
```yaml
dont-chroot: true
sequence:
- show:
  - welcome
  - summary
- exec:
  - preservefiles
- show:
  - finished
```
2. Use the following in `/etc/calamares/modules/preservefiles.conf`:
```yaml
files:
  - from: log
    dest: /root/install.log
  - from: config
    dest: /root/install.json
```
3. Click through to install.
4. See that the install fails with an error from the preservefiles job.
5. Run `cat /root/install.json` in a terminal to confirm that the global config dump worked.

**Expected behavior**
The error check is simply inverted -- a successful config dump produces an error, which it should not.

**Additional context**
The error check at [PreserveFiles.cpp#L140](https://github.com/calamares/calamares/blob/v3.2.30/src/modules/preservefiles/PreserveFiles.cpp#L140) needs to be inverted.
