### ISSUE TITLE
specify defaultGroup exepections

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#1523]
**Is your feature request related to a problem? Please describe.**
If a group listed in defaultGroup doesn't exist it currently gets silently autocreated. This lead to groups getting created that shouldn't be created (certainly not as !system groups).

Specifically samba used to be on an ISO and the user was default added to the sambashare (system) group to set up usershares. Later samba was removed from the default installation which lead to the group no longer existing and calamares going "oh my, I better create one". It did so without --system switch so now installations have random sambashare groups for no good reason.

**Describe the solution you'd like**
Either a bool toogle to disable group creation if it doesn't exist or...

better yet let the list entries be objects to control group expectations:

```
defaultGroups:
  - adm
  - foo:
      must_exist: false
      system: true
  - bar:
      must_exist: true
  - foobar:
      must_exist: false
      system: false
```

Where the musts are assertions leading to install failures and system controls if groupadd is invoked with `--system` or without.

@adriaandegroot did mention that it's very edge-case to create groups via cala to begin with, and I agree, so I'd also be fine with a toggle that maybe even is off by default

**Comment by adriaandegroot** [comment]
With a slight tweak to the format it's much easier to specify and parse, so it'll be

```
defaultGroups:
  - adm
  -   name: foo 
      must_exist: false
      system: true
  -   name: bar
      must_exist: true
  -   name: foobar
      must_exist: false
      system: false
```
