### ISSUE TITLE
Netinstaller not handling multiple nested selectable packages 

### ISSUE THREAD

**Issue by codesardine** [calamares/calamares#1535]
Pre selected packages via yaml work, in this case ( BASE ), manually selected packages on the UI fail to install.

Link to the package file:
https://gitlab.manjaro.org/packages/community/jade/calamares-netinstall-settings/-/blob/master/netinstall-software.yaml

**Comment by abucodonosor** [comment]
Can you please post a log where that fails and explain what you select?

Also, I don't think that file is correct but besides that, each nested subgroup is set as hidden.

This ort stuff is kinda wrong and pointless:

```
subgroups:
        - name: "Chromium"
          description: "Default"
          critical: false
          hidden: false
          selected: true
          expanded: false
          subgroups:
                hidden: true
                packages:
                    - chromium

````

What is the point of that?

You set a subgroup with a description etc then an incomplete subgroup hidden with the package?

**Comment by abucodonosor** [comment]
Ok, I think I know what you are trying to do.

Have the main subgroup selectable and the nested one hidden to install the package, but in this case, your nested subgroup is wrong.

Since you select the nested subgroup from the main subgroup and the nested subgroup is 'just set hidden' nothing will happen bc no package is selected. What you really want is to have selected: true in the nested subgroups as well.

**Comment by adriaandegroot** [comment]
The netinstall documentation at https://github.com/calamares/calamares/blob/calamares/src/modules/netinstall/netinstall.conf#L280 shows what you're trying to do:
 - a nice name to display
 - a longer application description
 - no package names visible

As @abucodonosor points out, the syntax of your YAML is almost-but-not-quite right (so, the parsing could be improved to warn about things it doesn't understand, and/or the schema files improved to catch this problem). *subgroups* wants a **list**, and you're giving it just an object. So you need a `-`, and the subgroups must have a name, but it's ok to call them all the same:
```
          subgroups:
              - name: bogus
                hidden: true
                packages:
                    - chromium
```

**Comment by abucodonosor** [comment]
@adriaandegroot 

```
    selected: true

```

is needed for the second subgroup too since is set to hidden. ( unless I'm missing something and selected defaults to true now for such a scenario )

**Comment by adriaandegroot** [comment]
It just **happens** that the one I picked as the example has a parent with `selected: true` so the subgroup I show inherits that from its parent; good catch. Yes, you'll need to set `selected: true` in those bogus subgroups and it's safest to do that explicitly in each of them.

**Comment by abucodonosor** [comment]
@adriaandegroot 

I'm not really sure this is inherited from the parent subgroup.

````

- name: "Browsers"
  critical: false
  hidden: false <-- user selectable, allows to see the subgroup
  selected: false <-- not default
  expanded: true
  subgroups:
        - name: "Chromium"
          description: "Default"
          critical: false
          hidden: false <-- user selectable
          selected: true <-- auto-selected , which allow to select the nested subgoup
          expanded: false
          subgroups:
                - name: ....
                description: .....
                hidden: true <-- not user selectable or visible
missing > selected: true <-- would cause the package to be selected & installed, without nothing happens.
                packages:
                    - chromium
```

Maybe I'm missing something but each subgroup/nested subgroup is set to hidden needs a default since the user cannot change anything nor see the subgroup. So even allowed to be selected from the parent subgroup it still needs it's own defaults to work.
