### ISSUE TITLE
In a / and /home partition layout, installing succeeds but on a reinstall Replace Partition the /home replace checkbox malfunctions

### ISSUE THREAD

**Issue by dominichayesferen** [calamares/calamares#1609]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
Feren OS is planning on employing a new partition layout in Calamares by default consisting of:
One / ext4 partition
One /home partition

However, after doing a successful Erase Disk install with that partitioning, if I then proceed to do it again but this time opt for Replace Partition and select the / partition, the checkbox for using the existing /home as /home for the new install appears as normal, but ticking it does nothing at all. The installer will still outline in the next page that the partitions will be a split of that / portion into a / and /home rather than it doing what the checkbox said it'd do.

**To Reproduce**
1. Have a partition.conf like this:
```
efiSystemPartition: "/boot/efi"
enableLuksAutomatedPartitioning: false
drawNestedPartitions: true

userSwapChoices:
    - suspend

partitionLayout:
    - name: "ferenos"
      filesystem: "ext4"
      mountPoint: "/"
      size: 35%
      minSize: 14G
    - name: "userstorage"
      filesystem: "ext4"
      mountPoint: "/home"
      size: 100%
      minSize: 10G
      
requiredStorage: 24
```

2. Erase Disk and install the OS normally with this Calamares configuration change implemented
3. Do this again but this time instead of Erase Disk choose Replace Partition and select the / from the new installation
4. Tick the checkbox for it using /home and see absolutely nothing occur

**Expected behavior**
The /home partition would be used in the reinstall as the checkbox promises

**Additional context**
