### ISSUE TITLE
Fix reported name for Python modules in subdirs

### ISSUE THREAD

**Issue by adriaandegroot** [calamares/calamares#1641]
This applies to the CMake parts that are used by *calamares-extensions* repo (which are installed from the Calamares repo, which is why the issue is here). The idea is that for external modules (e.g. those in *calamares-extensions*) there are simple / usable CMake macros to build a module.

In the extensions repo, the report on modules looks like this:

```
-- Found  module: mobile
   TYPE: viewmodule
   LINK_LIBRARIES: 
   LINK_PRIVATE_LIBRARIES: 
   PLUGIN_DESTINATION: lib/calamares/modules/mobile
   CONFIGURATION_FILES: mobile.conf => [Build directory only]
   RESOURCES: mobile.qrc

-- Found  module: modules/slowpython
   TYPE: jobmodule
   MODULE_DESTINATION: lib/calamares/modules/slowpython
   CONFIGURATION_FILES: slowpython.conf => [Build directory only]
```

Notice that the name, e.g. the bit after `Found module:`, is a bit odd: *modules/slowpython* is not actually the name, there's an extra *modules/* in there. This name confusion does not show up with other modules in the extensions repo, so it is probably related to being-a-Python-module.

So the issue / feature is: improve the reported "name" of a (Python) module when it lives in a subdirectory, to be only the last part of the directory path / the actual module name.
