### ISSUE TITLE
Custom partition layout not working as expected

### ISSUE THREAD

**Issue by linlinger** [calamares/calamares#1759]
> Hi! Thank you for helping improve Calamares. If you are seeing a problem in installing a specific distribution, you should **probably** report the problem in the distribution's bug tracker, first. That helps filter out issues with packaging, mis-configuration, etc. that Calamares has no control over. If you are a distribution packager or maintainer, this page is for you.

**Describe the bug**
A clear and concise description of what the bug is. Please include 32/64 bit machine details, EFI/BIOS details, and disk setup.
I specified a custom partition layout in partition in partition.conf and below is the custom partition layout I specified
```
partitionLayout:
     - name: "system"
       filesystem: "ext4"
       mountPoint: "/"
       size: 15G
     - name: "home"
       filesystem: "ext4"
       mountPoint: "/home"
       size: 80%
     - name: "backup"
       filesystem: "ext4"
       mountPoint: "/backup"
       size: 20%
```
And it works only the first time when I choose Replace a partition option with a partition or empty space selected.

![custom partition works when selecting replace a partituion option](https://user-images.githubusercontent.com/32541118/130214719-c12e9774-f7bb-496a-bf4b-cfaa900e2cdb.png)
 When I select other options and re-select Replace a partition. The custom partition could not be loaded. What I got is a big / partition. I have to restart Calamares
OS info
Running in a VirtualBox VM
Arch Linux with Xfce4 desktop installed come with customization
Boot from UEFI and MBR
Calamares Version :3.2.41.1

**To Reproduce**
1. Go to /etc/calamares/modules/partition.conf add custom partition as I mentioned above
2.Launch Calamares
3. Click On next until partitioning 
4. Click erase the disk 
4. See error:custom partition is not being applied

**Expected behavior**
The partition should be applied when I erasing the whole disk
**Screenshots and Logs**
If applicable, add screenshots to help explain your problem. Calamares has an installation log (usually `~/.cache/calamares/session.log`), please check it for confidential information and attach it if possible.
![Custom layout couldn't be loaded properly](https://user-images.githubusercontent.com/32541118/130217609-8bf41eea-5b62-4b14-b4fd-e806703c768b.png)
![custom partition works when selecting replace a partituion option](https://user-images.githubusercontent.com/32541118/130217614-01805fe6-2117-49ae-b1eb-63a2ab7cec97.png)
![not working again](https://user-images.githubusercontent.com/32541118/130217620-605298c6-9037-4343-abfc-8ed7bb9f5a10.png)
contents in session.log
=== START CALAMARES 3.2.41.1-1.1

**Additional context**
No 4 now
