### ISSUE TITLE
Patch mount and fstab modules to allow for installation without subvol=/@

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#1837]
Hi there, it's me from #calamares:kde.org in the conversation with @adriaandegroot  about the patch that he kindly added to https://github.com/calamares/calamares/tree/btrfs-no-subvolume . This gets me very close to what I wanted. In `mount.conf`
```
btrfsSubvolumes:
    - mountPoint: /
      subvolume: ""
    - mountPoint: /.snapshots
      subvolume: /@snapshots
    - mountPoint: /home
      subvolume: /@home
    - mountPoint: /var
      subvolume: /@var
```

This gives me an `/etc/fstab` on the installed system like this:
```
UUID=c41d9810-bc7c-45b8-a9dc-2a1a1cb8806e /              btrfs   subvol=,defaults,noatime,space_cache,autodefrag,compress=zstd 0 0
UUID=c41d9810-bc7c-45b8-a9dc-2a1a1cb8806e /.snapshots    btrfs   subvol=/@snapshots,defaults,noatime,space_cache,autodefrag,compress=zstd 0 0
UUID=c41d9810-bc7c-45b8-a9dc-2a1a1cb8806e /home          btrfs   subvol=/@home,defaults,noatime,space_cache,autodefrag,compress=zstd 0 0
UUID=c41d9810-bc7c-45b8-a9dc-2a1a1cb8806e /var           btrfs   subvol=/@var,defaults,noatime,space_cache,autodefrag,compress=zstd 0 0
```
The only little detail is the `subvol=,` which might be the same as if the `subvol` option didn't appear at all, but I think it might be best for it to not appear at all in this case.

Thanks a lot for the help!
