### ISSUE TITLE
Allow for creating deeper btrfs subvolumes

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#1838]
Hi there, I would like to create a Btrfs subvolume scheme similar to what openSUSE uses by default:

```
localhost:/home/sam # cat /etc/fstab 
UUID=d7cfe18a-6848-4bdb-91a0-2aa969eb8a18  /                       btrfs  defaults                      0  0
UUID=d7cfe18a-6848-4bdb-91a0-2aa969eb8a18  /var                    btrfs  subvol=/@/var                 0  0
UUID=d7cfe18a-6848-4bdb-91a0-2aa969eb8a18  /usr/local              btrfs  subvol=/@/usr/local           0  0
UUID=d7cfe18a-6848-4bdb-91a0-2aa969eb8a18  /srv                    btrfs  subvol=/@/srv                 0  0
UUID=d7cfe18a-6848-4bdb-91a0-2aa969eb8a18  /root                   btrfs  subvol=/@/root                0  0
UUID=d7cfe18a-6848-4bdb-91a0-2aa969eb8a18  /opt                    btrfs  subvol=/@/opt                 0  0
UUID=d7cfe18a-6848-4bdb-91a0-2aa969eb8a18  /home                   btrfs  subvol=/@/home                0  0
UUID=d7cfe18a-6848-4bdb-91a0-2aa969eb8a18  /boot/grub2/x86_64-efi  btrfs  subvol=/@/boot/grub2/x86_64-efi  0  0
UUID=d7cfe18a-6848-4bdb-91a0-2aa969eb8a18  /boot/grub2/i386-pc     btrfs  subvol=/@/boot/grub2/i386-pc  0  0

localhost:/home/sam # btrfs sub list /
ID 256 gen 114 top level 5 path @
ID 257 gen 114 top level 256 path var
ID 258 gen 111 top level 256 path usr/local
ID 259 gen 111 top level 256 path srv
ID 260 gen 114 top level 256 path root
ID 261 gen 111 top level 256 path opt
ID 262 gen 114 top level 256 path home
ID 263 gen 111 top level 256 path boot/grub2/x86_64-efi
ID 264 gen 109 top level 256 path boot/grub2/i386-pc
```

However, the deeper levels can't be created with Calamares because the top-level folder doesn't exist yet. For example, this `mount.conf` fails because `/usr` and `/boot` haven't been generated yet.
```
    - mountPoint: /
      subvolume: /@
    - mountPoint: /var
      subvolume: /@/var
    - mountPoint: /usr/local
      subvolume: /@/usr/local
    - mountPoint: /srv
      subvolume: /@/srv
    - mountPoint: /root
      subvolume: /@/root
    - mountPoint: /opt
      subvolume: /@/opt
    - mountPoint: /home
      subvolume: /@/home
    - mountPoint: /boot/grub2/x86_64-efi
      subvolume: /@/boot/grub2/x86_64-efi
    - mountPoint: /boot/grub2/i386-pc
      subvolume: /@/boot/grub2/i386-pc 
```

Thanks for the help! Please let me know if I didn't explain myself well.

**Comment by adriaandegroot** [comment]
There are ways in which this conflicts / confuses with #1837 . What we did there was allow **empty** subvolume-names, like
```
    - mountPoint: /
      subvolume: ""
```
which skips the creation of the subvolume for / **and** skips the `subvol=` line in fstab. I can't tell from the *btrfs-subvolume(8)* manpage exactly how the *name* of the subvolume is interpreted, or even what '/@/usr/local` is supposed to mean.

**Comment by geckolinux** [comment]
I also tried a hybrid `mount.conf` scheme based on the improvement in #1837 :
```
btrfsSubvolumes:
    - mountPoint: /
      subvolume: ""
    - mountPoint: /var
      subvolume: /var
    - mountPoint: /usr/local
      subvolume: /usr/local
    - mountPoint: /srv
      subvolume: /srv
    - mountPoint: /root
      subvolume: /root
    - mountPoint: /opt
      subvolume: /opt
    - mountPoint: /home
      subvolume: /home
    - mountPoint: /boot/grub2/x86_64-efi
      subvolume: /boot/grub2/x86_64-efi
    - mountPoint: /boot/grub2/i386-pc
      subvolume: /boot/grub2/i386-pc
```
This also resulted in an error on the first nested subvolume:
```
Boost.Python error in job "mount".
Command '['btrfs', 'subvolume', 'create', '/tmp/calamares-root-uplgc1oc/usr/local']' returned non-zero exit status 1.
None

Traceback:
File "/usr/lib64/calamares/modules/mount/main.py", line 250, in run
    mount_partition(root_mount_point, partition, partitions)

  File "/usr/lib64/calamares/modules/mount/main.py", line 196, in mount_partition
    subprocess.check_call(["btrfs", "subvolume", "create",

  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
```

I also tried without a leading `/` ...
```
    - mountPoint: /usr/local
      subvolume: usr/local
```
...but it also resulted in a similar error.

I also tried this:
```
btrfsSubvolumes:
    - mountPoint: /
      subvolume: ""
    - mountPoint: /var
      subvolume: /var
    - mountPoint: /usr/local
      subvolume: /usr-local
    - mountPoint: /srv
      subvolume: /srv
    - mountPoint: /root
      subvolume: /root
    - mountPoint: /opt
      subvolume: /opt
    - mountPoint: /home
      subvolume: /home
    - mountPoint: /boot/grub2/x86_64-efi
      subvolume: /boot-grub2-x86_64-efi
    - mountPoint: /boot/grub2/i386-pc
      subvolume: /boot-grub2-i386-pc
```

But this resulted in a broken GRUB, because the filesystem hierarchy was wrong:
![Screenshot from 2021-12-03 08-32-27](https://user-images.githubusercontent.com/2692138/144612293-23b76b58-e230-4043-a65a-90364a349815.png)

-------------------

So Btrfs subvolumes do have a sense of hierarchy. https://wiki.archlinux.org/title/Btrfs#Subvolumes
> Each Btrfs file system has a top-level subvolume with ID 5. It can be mounted as / (by default), or another subvolume can be mounted instead. Subvolumes can be moved around in the filesystem and are rather identified by their id than their path. 

https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Subvolumes

> ### Flat
> Subvolumes are children of the top level subvolume (ID 5), typically directly below in the hierarchy or below some directories belonging to the top level subvolume
> 
> ### Nested
> Subvolumes are located anywhere in the file hierarchy, typically at their desired locations (that is where one would manually mount them at in the flat schema), especially below other subvolumes that are not the top-level subvolume
> 
> ### Mixed
> Of course the above two basic schemas can be mixed at personal convenience, e.g. the base structure may follow a flat layout, with certain parts of the filesystem, being placed in nested subvolumes.

So the basic issue seems to be that this isn't a completely linear process, the `/usr` and /`boot/grub2` directories would have to be created or unpacked first onto the target filesystem before nested subvolumes can be created there.
