### ISSUE TITLE
preservefiles module do not accept - src: usage

### ISSUE THREAD

**Issue by killajoe** [calamares/calamares#1851]
Calamares 3.2.49.1

Just tried to switch from umount module to preservefiles module to copy a custom created log over to target.
adding preservefiles to the exec schedule  in settings.conf at the very end just beforee umount module.
setup preservefiles.conf like so:
```
dontChroot: false

files:
  - src: /home/liveuser/endeavour-install.log
    dest: /var/log/endeavour-install.log
    perm: root:wheel:644
```

Logic should be right to work for this:

```
- *src*, to refer to a path interpreted in the host system.
```
```
- a map with a *dest* key. The *dest* value is a path interpreted in the
target system (if dontChroot is true, in the host system).
```
i can use the full path option like:
`- /var/log/logfile.txt`

and  `- from:` is working also, independently if i use chrooted or not.. 
What means that `dest:` is working always as target (putting `@@ROOT@@` to dest path let module fail to load)

So the issue is with `- src:`  

tried to find related part handling src in 
[PreserveFiles.cpp](https://raw.githubusercontent.com/calamares/calamares/calamares/src/modules/preservefiles/PreserveFiles.cpp)
show no mention for src also (but whoami to understand the code fully ;)
