### ISSUE TITLE
ssdExtraMountOptions not being applied?

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#1883]
Hi, with  Calamares 3.2.49.1 on openSUSE Tumbleweed I noticed on my personal installation on a machine with an NVMe drive that the `ssdExtraMountOptions` apparently aren't applied:

fstab.conf
```
mountOptions:
    default: defaults,noatime
    btrfs: defaults,noatime,space_cache=v2,autodefrag,compress=zstd
    btrfs_swap: defaults

ssdExtraMountOptions:
    btrfs: discard=async,ssd
```

/etc/fstab
`UUID=ffe3795e-bfe5-4856-8048-61e9d364af96 /              btrfs   defaults,noatime,space_cache=v2,autodefrag,compress=zstd 0 0`

Or do the SSD options only apply only to older SSD (non-NVMe) drives? Or is this due to #1846 being implemented? Thanks for the help!
