### ISSUE TITLE
Root partition label is always "root"  even if partition layout in conf names it differently

### ISSUE THREAD

**Issue by santoshmahto7** [calamares/calamares#1904]
**Describe the bug**

In target image, root partition label are not picked up from parition layout specified in partition.conf instead always set to "root"
e.g if parition.conf specify layout as below where we name root partition as rootfs-A then it is ignored and target rootfs is named "root" which is incorrect
```
partitionLayout:
    - name: "efi"
      filesystem: "fat32"
      mountPoint: "/tmp/A/efi"
      size: 256MiB
    - name: "rootfs-A"
      type: "4f68bce3-e8cd-4db1-96e7-fbcaf984b709"
      filesystem: "ext4"
      mountPoint: "/tmp/A"
      size: 10GiB
    - name: "var-A"
```

**Expected behavior**
Target rootfs should be named as specified in partition layout in settings
