### ISSUE TITLE
greetd: Error while creating default desktop environment

### ISSUE THREAD

**Issue by Sunderland93** [calamares/calamares#1937]
**Describe the bug**
I try to install Sway with `greetd` and `tuigreet` on my custom Ubuntu 22.04. In my `displaymanager.conf` I have define `greetd` as display manager and Sway as default desktop:

```
displaymanagers:
  - greetd

defaultDesktopEnvironment:
    executable: "sway"
    desktopFile: "sway"

basicSetup: false
sysconfigSetup: false
```
but installer is falling with error (see screenshot)

**To Reproduce**
1. Set greetd as display manager in /etc/calamares/modules/displaymanager.conf
2. Run the Calamares installer (in my ISO it runs after booting, but can run with Win+i keybinding)
3. Proceed to install
4. See error on add user to autologin step

**Expected behavior**
Sway should be added in greetd's `config.toml` and installation should finish successfully

![Screenshot_20220501_145933](https://user-images.githubusercontent.com/11344982/166143050-6cfffc47-fc61-4db9-8bde-d01b6cd0adeb.png)

OS: Ubuntu 22.04 with Sway (my own ISO: https://mega.nz/file/FBpXyYCI#QARVvUWDLfEtKLkOFgoVXiWrjl4YhNlOYuerUkcFfNk)
Calamares version: 3.2.56
Session log: https://mega.nz/file/5JJimQRa#6svjShSJOY7pu3_4r6pLOnAjo4nKk5sGcLtQLcPCOyE
