### ISSUE TITLE
[ENHANCEMENT] - Allowing unpackfs module to manage multiple airootfs and vmlinuz-linux paths

### ISSUE THREAD

**Issue by D3vil0p3r** [calamares/calamares#2068]
**Is your feature request related to a problem? Please describe.**
I have two scenarios when I should install the system by Calamares:
1- Installation on a VM by attaching a .iso file
2- Burn the .iso file inside a USB key and install the system as bare metal (so no VM)

I noted that, in both of the cases, at the boot to the live environment, the `airootfs.sfs` and `vmlinuz-linux` (used in unpackfs module) are placed in different paths in the two scenarios shown above:
1. If we are installing in a VM attaching a .iso file:
  * `airootfs.sfs` file will be in `/run/archiso/bootmnt/arch/x86_64/`
  * `vmlinuz-linux` file will be in `/run/archiso/bootmnt/arch/boot/x86_64/`
2. If we are installing in bare-metal by using a USB key:
  * `airootfs.sfs` file will be in `<mounted-path-of-usb-key>/arch/x86_64/`
  * `vmlinuz-linux` file will be in `<mounted-path-of-usb-key>/arch/boot/x86_64/`

So, the main difference is that for VM, when the .iso is attached directly, as starting point is used `/run/archiso/bootmnt/` folder; when I use bare-metal with USB key, the starting point is a folder named with the name of USB key.

The content of `unpackfs.conf` module is:
```
unpack:
    -   source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
        sourcefs: "squashfs"
        destination: ""
    -   source: "/run/archiso/bootmnt/arch/boot/x86_64/vmlinuz-linux"
        sourcefs: "file"
        destination: "/boot/vmlinuz-linux"
```
so, it will cover only the Scenario 1.

Since I would like to cover both of the scenarios, and since I don't know why using a USB key, `airootfs.sfs` and `vmlinuz-linux` files are not placed in `/run/archiso/bootmnt/` (I tried both EFI and LEGACY methods), is it possible to implement `unpackfs` module in order to find a source file in multiple paths if in the first one cannot find anything?

Otherwise, people that are in the Scenario 2 are always forced to edit `unpackfs.conf` and edit manually the `airootfs.sfs` and `vmlinuz-linux` source paths.

Thank you in advance

**Comment by adriaandegroot** [comment]
This sounds like something that would be good in the *unpackfsc* module (in calamares-extensions), which is in C++ and much more nicely structured. We could just turn the *source* key into a list (if a string, it's a one-item list). Then the installation is defined as "first one of these that is found, use it".

**Comment by D3vil0p3r** [comment]
> This sounds like something that would be good in the _unpackfsc_ module (in calamares-extensions), which is in C++ and much more nicely structured. We could just turn the _source_ key into a list (if a string, it's a one-item list). Then the installation is defined as "first one of these that is found, use it".

Yes, the last sentence is what I meant. Thank you @adriaandegroot !

**Comment by D3vil0p3r** [comment]
@adriaandegroot is it also possible to define inside it as improvement a system environment variable as `$MOUNT_DIR` that corresponds to the directory path where the bootable USB key or .iso have been mounted? In order to have `unpackfs.conf` as:
```
unpack:
    -   source: "$MOUNT_DIR/arch/x86_64/airootfs.sfs"
        sourcefs: "squashfs"
        destination: ""
    -   source: "$MOUNT_DIR/arch/boot/x86_64/vmlinuz-linux"
        sourcefs: "file"
        destination: "/boot/vmlinuz-linux"
```
for example in the same way it is dealt in Archiso in the `archiso/syslinux/*.cfg` files with `%INSTALL_DIR%` variable (or that %INSTALL_DIR% value will be stored also in this `$MOUNT_DIR` variable?

Example of `archiso/syslinux/archiso_pxe-linux.cfg` file:
```
LABEL arch64_nbd
TEXT HELP
Boot Axyl install medium using NBD.
It allows you to install Axyl or perform system maintenance.
ENDTEXT
MENU LABEL Axyl install medium (x86_64, NBD)
LINUX /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
INITRD /%INSTALL_DIR%/boot/intel-ucode.img,/%INSTALL_DIR%/boot/amd-ucode.img,/%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
APPEND archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% archiso_nbd_srv=${pxeserver} checksum verify
SYSAPPEND 3

LABEL arch64_nfs
TEXT HELP
Boot the Axyl live medium using NFS.
It allows you to install Axyl or perform system maintenance.
ENDTEXT
MENU LABEL Axyl install medium (x86_64, NFS)
LINUX /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
INITRD /%INSTALL_DIR%/boot/intel-ucode.img,/%INSTALL_DIR%/boot/amd-ucode.img,/%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
APPEND archisobasedir=%INSTALL_DIR% archiso_nfs_srv=${pxeserver}:/run/archiso/bootmnt checksum verify
SYSAPPEND 3

LABEL arch64_http
TEXT HELP
Boot the Axyl live medium using HTTP.
It allows you to install Axyl or perform system maintenance.
ENDTEXT
MENU LABEL one install medium (x86_64, HTTP)
LINUX /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
INITRD /%INSTALL_DIR%/boot/intel-ucode.img,/%INSTALL_DIR%/boot/amd-ucode.img,/%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
APPEND archisobasedir=%INSTALL_DIR% archiso_http_srv=http://${pxeserver}/ checksum verify
SYSAPPEND 3
```
