### ISSUE TITLE
[Help] how do i add a flag to a partition in partitionLayout: in partition.conf

### ISSUE THREAD

**Issue by CosmicFusion** [calamares/calamares#2111]
my distribution requires /boot to have the "xbootldr/bls_boot/Linux Extended Boot" flag set.
```
partitionLayout:
    - name: ""
      filesystem: "fat32
      mountPoint: "/boot"
      size: 1G
    - name: ""
      filesystem: "btrfs"
      mountPoint: "/"
      size: 100%
```
So How would i do it?
