### ISSUE TITLE
[ENHANCEMENT] Support for GIF image extension on section conf files

### ISSUE THREAD

**Issue by D3vil0p3r** [calamares/calamares#2126]
**Is your feature request related to a problem? Please describe.**
I'm massively using Calamares on my custom OS and currently I created several sections based on software type (i.e., Utilities, Browser, Login Manager, and so on) where a user can select its favourite software to be installed.

On some of these sections, I used a .conf file that shows the section as follows:
![image](https://user-images.githubusercontent.com/83867734/232904434-a3e90a45-ac00-4ff5-bb5f-ddf5d7106af5.png)

This result can be reached by using a `.conf` file structured like:
```
#
# Configuration for Browser chooser in Calamares

mode: required

method: legacy

labels:
    step: "Browser"

items:

    - id: brave
      name: "Brave"
      description: "Web browser mainly focused on privacy."
      screenshot: "/etc/calamares/images/brave.png"

    - id: firefox
      # packages: [] # This item installs no packages
      name: "Firefox ESR"
      description: "Standalone web browser from mozilla.org."
      screenshot: "/etc/calamares/images/firefox.png"
```
I was wondering it could be wonderful if, on this kind of configuration, Calamares supports also GIF images in order to show for some seconds some more things on the software (i.e., for example the choice of the boot animation). 

**Describe the solution you'd like**
I would like to have GIF files supported on Calamares for the kind of sections shown above.

**Describe alternatives you've considered**
Currently there is no alternative.
