### ISSUE TITLE
ERROR: Installation failed: "Boost.Python error in job \"mount\"." in ext4 partitioning step

### ISSUE THREAD

**Issue by czardien** [calamares/calamares#2147]
**The bug**

I build Calamares release 3.2.61 with the following command and flags:

```
mkdir -p build
  cd build
  cmake .. \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DWITH_PYTHONQT=OFF \
  -DWITH_KF5DBus=OFF \
  -DBoost_NO_BOOST_CMAKE=ON \
  -DWEBVIEW_FORCE_WEBKIT=OFF \
  -DSKIP_MODULES="webview tracking interactiveterminal initramfs \
  initramfscfg dracut dracutlukscfg \
  dummyprocess dummypython dummycpp \
  dummypythonqt services-openrc \
  keyboardq localeq welcomeq"
  make
```

This is the settings file I use:

```
/etc/calamares/settings.conf
---
modules-search: [ local ]
sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - usersq
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - initcpiocfg
  - initcpio
  - removeuser
  - usersq
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - grubcfg
  - bootloader
  - preservefiles
  - umount
- show:
  - finishedq

branding: temperance
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
```

From a live ISO, I run Calamares, select the "Erase disk option" and select an ext4 partition plus a Swap file with the hibernate option. However, as the installation process starts, I run into an error in the very first step, when creating the ext4 partition.

The logs say:

```
=== START CALAMARES -1
2023-05-24 - 10:59:57 [1]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
    ERROR: Installation failed: "Boost.Python error in job \"mount\"." 
```

... and I get the following stacktrace, after I escape the HTML control characters:

```
<class 'Boost.Python.ArgumentError'>

Python argument types in libcalamares.utils.mount(str, str, str, list) did not match C++ signature: 

mount(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > device_path, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mount_point) 
mount(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > device_path, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mount_point, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filesystem_name) 
mount(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > device_path, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > mount_point, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filesystem_name, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > options)

Traceback: File "/usr/lib/calamares/modules/mount/main.py", line 251, in run mount_partition(root_mount_point, partition, partitions) 
File "/usr/lib/calamares/modules/mount/main.py", line 179, in mount_partition if libcalamares.utils.mount(device, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
``` 

The above seems to be coming from the mount python job at `/usr/lib/calamares/modules/mount/main.py`:

```
/usr/lib/calamares/modules/mount/main.py
---
    if fstype == "zfs":
        mount_zfs(root_mount_point, partition)
    else:  # fstype == "zfs", by the way that seems like a typo to me, it should probably say != 
        if libcalamares.utils.mount(device,
                                    mount_point,
                                    fstype,
                                    partition.get("options", "")) != 0:
            libcalamares.utils.warning("Cannot mount {}".format(device))
```

As I select the "Erase disk" option I would not expect any existing disk format/partition on my machine to have any consequence on the installation process.

The behaviour is the same without any Swap. 

**The machine**

I am not too sure what would be the relevant information to get from the machine, and how to get it, but if I get some assistance I'll be happy to ping that in the issue later on.

It's definitely a 64 bit machine though.  

**Other**

I dug through the code, and did some research online but couldn't find anything apparently related to my problem, so any assistance would be much appreciated! 

This is also my very first go at using Calamares, so apologies if there's any lack of information in my report.

_Edits_
* format stacktrace

**Comment by dalto8** [comment]
Can you share your `mount.conf` file?

This error is commonly caused by an error in `mount.conf` or using a `mount.conf` from 3.3.x with 3.2.x.

**Comment by czardien** [comment]
Hey, thank you so much for getting back to me. This is my `mount.conf` file, not sure I'm 100% on what it says:

```
/etc/calamares/modules/mount.conf
---
extraMounts:
    - device: proc
      fs: proc
      mountPoint: /proc
    - device: sys
      fs: sysfs
      mountPoint: /sys
    - device: /dev
      mountPoint: /dev
      options: [ bind ]
    - device: tmpfs
      fs: tmpfs
      mountPoint: /run
    - device: /run/udev
      mountPoint: /run/udev
      options: [ bind ]
    - device: efivarfs
      fs: efivarfs
      mountPoint: /sys/firmware/efi/efivars
      efi: true

btrfsSubvolumes:
    - mountPoint: /
      subvolume: /@
    - mountPoint: /home
      subvolume: /@home
    - mountPoint: /root
      subvolume: /@root
    - mountPoint: /srv
      subvolume: /@srv
    - mountPoint: /var/cache
      subvolume: /@cache
    - mountPoint: /var/log
      subvolume: /@log
    - mountPoint: /var/tmp
      subvolume: /@tmp

btrfsSwapSubvol: /@swap

mountOptions:
    - filesystem: default
      options: [ defaults, noatime ]
    - filesystem: efi
      options: [ defaults, umask=0077 ]
    - filesystem: btrfs
      options: [ defaults, noatime, compress=zstd ]
    - filesystem: btrfs_swap
      options: [ defaults, noatime ]
    - filesystem: ext4
      options: [ defaults, noatime, commit=60 ]
    - filesystem: xfs
      options: [ defaults, lazytime, noatime, attr2, inode64, logbsize=256k, noquota ]
    - filesystem: f2fs
      options: [ defaults, compress_algorithm=lz4, compress_chksum, atgc, gc_merge, lazytime ]
```

Does that help?
