### ISSUE TITLE
[packagechooser] netinstall-add method

### ISSUE THREAD

**Issue by udeved** [calamares/calamares#2261]
**Describe the bug**
If I set the packagechooser to netinstall-add, the netinstall module somehow gets a wrong datalist passed resulting is an empty item shown.
My suspicion would be, the GS value written does not match the netinstall required group data, the netgroup itself is  listitem[0] of netinstallAdd GS. I think only the actual netinstall data should be written to GS?  It would explain the attached screenshot, which is a slight showstopper atm.

**To Reproduce**
* set 'netinstall-add' in packagechooser, define some choice and netinstall item list in the conf
* example used:

```
items:
    - id: OpenRC
      name: openrc
      description: "OpenRC init system"
      screenshot: ":/images/calamares.png"
      netinstall:
        groups:
            - name: "OpenRC"
              description: "OpenRC init system"
              selected: false
              critical: true
              immutable: false
              expanded: true
              hidden: false
              packages:
                - audit-openrc
```

**Expected behavior**
The netinstall view should show the netgroup passed, and possible be expanded like set in the yaml

**Screenshots and Logs**
[![Screenshot-20231227-233359.png](https://i.postimg.cc/wjwsxRVm/Screenshot-20231227-233359.png)](https://postimg.cc/Hr7LBxFY)

**Additional context**
version 3.3.0 using qt5/kf5 artix linux build

**Comment by adriaandegroot** [comment]
That's a pretty clear description of the issue, thanks.

**Comment by dalto8** [comment]
You don't use `groups` with `netinstall-add`.  It basically takes the contents of a single group for each packagechooser item.

Try removing `groups` and not have array items directly under it. So:

```t
netinstall:
              name: "OpenRC"
              description: "OpenRC init system"
              selected: false
              critical: true
              immutable: false
              expanded: true
              hidden: false
              packages:
                - audit-openrc
```

**Comment by udeved** [comment]
> Try removing groups and not have array items directly under it. So:

Have you tried that?
That's not gonna fix it, no GS will be written, and a warning printed that it is not valid netinstall data if you remove the group.

**Comment by dalto8** [comment]
> Have you tried that?

For reference, here is the config for EndeavourOS which uses netinstall-add: https://raw.githubusercontent.com/endeavouros-team/calamares/calamares/data/eos/modules/packagechooser.conf

**Comment by udeved** [comment]
> You need to also take out the array below group.

Ok, this works, thanks, but I don't know if this is still a bug?
The netinstall data passed doesn't comply with the expected data and documentation. 
I guess it depends if this needs fixing or updating documentation.

**Comment by dalto8** [comment]
That is definitely how it was designed to work.  It adds a group and as a result expects the yaml to be the contents of a `group`.

That is what this means:
> #       The data in this field should follow the format of a group
> #       from the netinstall module documented in
> #       src/modules/netinstall/netinstall.conf.

Perhaps we could add an example to make it more clear.

**Comment by udeved** [comment]
> That is what this means

Yes, but the crucial detail is to not have a sequence like netinstall yaml, but a netinstall map.
anyhow, at least no show stopper any longer and I can move on. :)

**Comment by udeved** [comment]
@adriaandegroot 

I would probably make this a related feature request to have the yaml definitions in a online yaml file similar to netinstall for the packagechooser.
I doubt I have the time, but if, I give it a shot including the netinstall LoaderQueue. However, this would require the data source to be "fixed" to yaml netinstall definitions.

Possible example:

```
items:
    - id: Foo
      name: foo
      description: "Foo description"
      screenshot: ":/images/foo.png"
      netinstall:
        groupsUrl: myurl/data.yaml
```

[![Screenshot-20231228-041024.png](https://i.postimg.cc/VLmwcsr1/Screenshot-20231228-041024.png)](https://postimg.cc/WtWCGvwf)

Next screenshot would have application for a packagechooser item groupsUrl, where the init package definitions are loaded from url rather than local file.

[![Screenshot-20231228-041121.png](https://i.postimg.cc/zXVjvKRk/Screenshot-20231228-041121.png)](https://postimg.cc/GHnYSBKB)
