### ISSUE TITLE
[Regression] [mount] Btrfs root without subvolume no longer works

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#2278]
Hi, it looks like something changed between my last distro release (based on openSUSE Tumbleweed) that was using Calamares 3.2.59 and my current build that uses Calamares 3.2.62. This is my `mount.conf` , which takes advantage of the improvement that was implemented in #1837 :

```
btrfsSubvolumes:
    - mountPoint: /
      subvolume: ""
    - mountPoint: /.snapshots
      subvolume: /.snapshots
    - mountPoint: /home
      subvolume: /home
    - mountPoint: /root
      subvolume: /root
    - mountPoint: /var
      subvolume: /var
```

With this the installation now proceeds to about 40% and then fails with `rsync failed with error code 11.`  This is a bogus error, there's still more than enough space available. But `dmesg` shows this after the Btrfs filesystem creation step but _before_ the `rsync` failure:
```
[  241.976184] BTRFS info (device sda1): first mount of filesystem 1dc961fc-201e-4cb7-8a1e-abc4ad97626b
[  241.976200] BTRFS info (device sda1): using crc32c (crc32c-intel) checksum algorithm
[  241.976208] BTRFS error (device sda1): unrecognized mount option 'subvol'
[  241.977311] BTRFS error (device sda1): open_ctree failed
```

And the cause of the error is explained in the Calamares log:

```
    Starting job "mount" ( 10 / 36 ) 
...
    .. Running ("mount", "-t", "btrfs", "-o", "subvol=,", "/dev/sda1", "/tmp/calamares-root-qoko1ckw/") 
    .. Target cmd: ("mount", "-t", "btrfs", "-o", "subvol=,", "/dev/sda1", "/tmp/calamares-root-qoko1ckw/") Exit code: 32 output:
 mount: /tmp/calamares-root-qoko1ckw: wrong fs type, bad option, bad superblock on /dev/sda1, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
    .. Running ("udevadm", "settle") 
    .. Running ("sync") 
WARNING: [PYTHON JOB]: "Cannot mount /dev/sda1" 
```

Here's the complete log: [calamares.log.txt](https://github.com/calamares/calamares/files/14072484/calamares.log.txt)

This is a regression, because the same `mount.conf` worked as expected in my last release a year and half ago.

To test it I used the standard Calamares `mount.conf` and the installation completed successfully, but that subvolume layout won't work for Snapper rollbacks.

Please let me know if you need any more information. Thanks!
