### ISSUE TITLE
How to enable `fast_commit`

### ISSUE THREAD

**Issue by es20490446e** [calamares/calamares#2388]
At [partition.conf](https://github.com/calamares/calamares/blob/calamares/src/modules/partition/partition.conf) you can set filesystem features.

But if I do:
```
partitionLayout:
    name: "root"
    filesystem: "ext4"
    mountPoint: "/"
    size: 100%
    features:
        fast_commit: true
```

Then after installation I do:
```
tune2fs -l /dev/drivepartition | grep features
```

I don't see `fast_commit` in the list.

What's the proper way to achieve this? Maybe it can be better documented.
