### ISSUE TITLE
Allow BtrFS subvolume config with Snapper

### ISSUE THREAD

**Issue by ghost** [calamares/calamares#525]
Jira issue originally created by user sb56637:

Hi everyone,

So it looks like I am definitely migrating to Calamares for my GeckoLinux spin of openSUSE. (The old yast2-live-installer is being completely dropped and unsupported by openSUSE, and major bugs are starting to crop up as the openSUSE distro continues to involve.) Calamares is a great alternative that **almost** has feature parity with the old yast2-live-installer. But the only missing feature in Calamares is a way to configure BtrFS subvolumes with a simple Snapper configuration for automatic snapshots and GRUB2 boot environments integration. From there, openSUSE has a nice graphical Snapper tool to manage snapshots, but it only works if the underlying snapper config is already created. Would it be possible to integrate this into Calamares?

Thanks a lot!

**Comment by abucodonosor** [comment]
well that feature seems to have two parts.

Add snapper support ( which need to be kind generic )
And then add 'snapper-suse' modules to work with existing Suse tools , aka YaST

Right ?

**Comment by abucodonosor** [comment]
this one could be combined with #483

**Comment by abucodonosor** [comment]
also maybe with #807

**Comment by abucodonosor** [comment]
Ok we need someone from Suse for YaST support.

Suse itself has patched grub to work with his package manager , YaST and grub ..

**Comment by polarathene** [comment]
Arch Linux also has`grub-btrfs` and `snap-pac` for pre/post Pacman package manager hooks integration.

So in addition the SUSE one, I guess a ArchLinux module could be done as well? 

The original user who raised the issue in JIRA isn't subscribed to this issue since the migration to Github, not sure what their Github profile is to tag them for their input..

**Comment by geckolinux** [comment]
@polarathene Hi, subscribed. I would still love to see support for this!

**Comment by Conan-Kudo** [comment]
Note that Fedora also has the same support that SUSE has with its `grub2` package and that Arch has with the `grub-btrfs` package. So this would be useful there too.

**Comment by geckolinux** [comment]
Bit of an update: Thanks to the `shellprocess` module I was able to make it setup the Snapper config the way I want it by default for end users:

````
script:
    - "-snapper --no-dbus create-config -f btrfs @@ROOT@@"
    - "-snapper --no-dbus -c @home create-config -f btrfs @@ROOT@@home"
    - "-snapper --no-dbus -c @home set-config 'TIMELINE_CREATE=yes'"
    - "-snapper --no-dbus -c root set-config 'TIMELINE_CREATE=no'"
````

It's still a bit of a hack, since if the user specifies a non-Btrfs root FS then the commands fail, but I don't think it would do any harm in that case.

**Comment by geckolinux** [comment]
Fixed/worked-around with `shellprocess` and the fix from #1838 .

----------------

`mount.conf`

```
btrfsSubvolumes:
    - mountPoint: /
      subvolume: ""
    - mountPoint: /.snapshots
      subvolume: /.snapshots
    - mountPoint: /home
      subvolume: /home
    - mountPoint: /root
      subvolume: /root
    - mountPoint: /var
      subvolume: /var
    - mountPoint: /boot/grub2/x86_64-efi
      subvolume: /boot/grub2/x86_64-efi
    - mountPoint: /boot/grub2/i386-pc
      subvolume: /boot/grub2/i386-pc
```

-------------

`shellprocess.conf`

```
script:
    - "-umount @@ROOT@@.snapshots"
    - "-rm -r @@ROOT@@.snapshots"
    - "-snapper --no-dbus create-config -f btrfs @@ROOT@@"
    - "-snapper --no-dbus -c home create-config -f btrfs @@ROOT@@home"
    - "-snapper --no-dbus -c home set-config 'TIMELINE_CREATE=yes'"
    - "-snapper --no-dbus -c root set-config 'TIMELINE_CREATE=no'"
```
---------------

Also needs `SUSE_BTRFS_SNAPSHOT_BOOTING="true"` in `/etc/default/grub` .
