### ISSUE TITLE
fstab generator setting wrong uuid for encrypted systems for root fs on Calamares 3.1.1

### ISSUE THREAD

**Issue by n3rdopolis** [calamares/calamares#772]
Hi

It seems, at least with Debian, that the fstab generator, when I install an encrypted system with my own built Calamares, that it is adding the wrong UUID into /etc/fstab for the root fs . EDIT: I am mistaken slightly, the `/usr/share/initramfs-tools/hooks/cryptroot` script wants the UUID for the one with the actual FS (  /dev/dm-0 ), based on the way it parses /etc/fstab, but when it comes to mounting the filesystem with fstab, fstab is fine with the one for /dev/sda1 or /dev/dm-0

On a test system, I have (I will only do partial UUIDs, since I don't have copy/paste out of this VM)
```
68adf7f7-xxxx-xxxx-xxxx-xxxxxxxxxxxx = /dev/dm-0
571609f4-xxxx-xxxx-xxxx-xxxxxxxxxxxx = /dev/sda1   (ext4)

d5cb590e-xxxx-xxxx-xxxx-xxxxxxxxxxxx = /dev/dm-1
e14433e3-xxxx-xxxx-xxxx-xxxxxxxxxxxx = /dev/sda2 (swap)
```

For some reason, in /etc/fstab it was 
```
UUID=571609f4-xxxx-xxxx-xxxx-xxxxxxxxxxxx     /     ext4    defaults,noatime    0    1
```
That UUID is for the direct device /dev/sda1 that has the LVM partition on it, and not for /dev/dm-0 which is the one with the actual ext4 file system.
 
This caused the initramfs to not have a /conf/conf.d/cryptroot, and fail to unlock automatically, and drop to the initramfs shell. 

Mounting from a live cd, changing it to 68adf7f7-xxxx-xxxx-xxxx-xxxxxxxxxxxx, chrooting, and updating the initramfs, and restarting allowed it to boot.

If this can't be replicated, Is there any chance I have Calamares configured wrong? ($INSTALLDIR  = /opt)
```
cmake -Wno-dev .. -DCMAKE_INSTALL_PREFIX=$INSTALLDIR -DCMAKE_PREFIX_PATH=$INSTALLDIR  -DCMAKE_BUILD_TYPE=Release -DWITH_PARTITIONMANAGER=1 -DWEBVIEW_FORCE_WEBKIT=1
```

Thanks

**Comment by n3rdopolis** [comment]
settings file:
```
# Configuration file for Calamares
# Syntax is YAML 1.2
---
modules-search: [ local ]
sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - luksbootkeyfile
  - initramfscfg
#  - luksopenswaphookcfg
#  - dracutlukscfg
#  - plymouthcfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services
  - packages
#  - dracut
  - initramfs
#  - grubcfg
  - bootloader
  - umount
- show:
  - finished
branding: default
prompt-install: false
dont-chroot: false
```
fstab config:
```
---
mountOptions:
    default: defaults,noatime
    btrfs: defaults,noatime,space_cache,autodefrag
ssdExtraMountOptions:
    ext4: discard
    jfs: discard
    xfs: discard
    swap: discard
    btrfs: discard,compress=lzo
crypttabOptions: luks,keyscript=/bin/cat
# For Debian and Debian-based distributions, change the above line to:
# crypttabOptions: luks,keyscript=/bin/cat
```
