### ISSUE TITLE
Use fstrim.timer instead of "discard" flag in /etc/fstab

### ISSUE THREAD

**Issue by sevendogsbsd** [calamares/calamares#798]
#### Submission type

  - [ ] Bug report
  - [X] Feature Request

#### Info regarding which version of Calamares is used, which Distribution

>17.0.4 (Xfce)

#### Provide information on how the disks are set up, in detail, with full logs of commands issued 

>/ and /swap on /dev/sda, /home on /dev/sdb

#### What do you expect to have happen when Calamares installs?

>/etc/fstab is created without the "discard" mount flag

#### Describe the issue you encountered

>No issue - the discard mount flag in /etc/fstab is no longer recommended and the "fstrim.timer" systemd unit should be used instead.

#### Steps to reproduce the problem

>Install current version of Manjaro

#### Include the installation.log:

>NA

**Comment by abucodonosor** [comment]
No is up2 the distributor or you do do that .. 

You can do that from fstab.conf ..

see also https://github.com/calamares/calamares/issues/667

**Comment by philmmanjaro** [comment]
Default **fstab.conf** is:

```
---
mountOptions:
    default: defaults,noatime
    btrfs: defaults,noatime,space_cache,autodefrag
ssdExtraMountOptions:
    ext4: discard
    jfs: discard
    xfs: discard
    swap: discard
    btrfs: discard,compress=lzo
crypttabOptions: luks
# For Debian and Debian-based distributions, change the above line to:
# crypttabOptions: luks,keyscript=/bin/cat
```
Which file system needs those changes?
