### ISSUE TITLE
add timeout setting to contextualprocess and shellprocess

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#897]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

contextualprocess currently always times out after 10 seconds. when the subproc needs to do networkbound-IO that time out can easily trigger though. would be lovely if there was a setting for that (ideally per-command)

e.g.

```
efi:
  - cmd: wget foo
    timeout: 3600
  - rm -rf /usr
```
