### ISSUE TITLE
contextualprocess wildcard to match all

### ISSUE THREAD

**Issue by apachelogger** [calamares/calamares#906]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

#### Describe the issue you encountered

The contextualprocess module currently has three possible keys `efi`, `bios`, and `""`. What would be lovely to have is a wildcard key `"*"` matching all types (in addition to their specific keys and ideally run after the specific processes). The specific use case we have is that we have a special repo in the rootfs which contains bootloader packages for when the system is being installed without internet access. We'll run specific install code for the system mode and then a global cleanup routine to discard the repo from the rootfs (serves no purpose after installation).

e.g.

```
firmwareType:
    efi:
    - ...
    - apt install grub-efi

    bios:
    - ...
    - apt install grub-pc

    "*":
    # clean up preinstall repo for all types
    - rm -rfv /var/lib/preinstalled-pool && apt-get update
```

**Comment by adriaandegroot** [comment]
Use a shellprocess instance (after your contextualprocess instance) to do that, e.g.

```
instances:
 - id: efiinstall
   module: contextualprocess
   config: efiinstall.conf
 - id: eficleanup
   module: shellprocess
   config: eficleanup.conf
sequence:
  - exec:
   - contextualprocess@efiinstall
   - shellprocess@eficleanup
```

The sequencing you want is provided by *sequence* in the `settings.conf` file. Matching on all values is done by not matching at all, but just running the commands. I can imagine that a wildcard-match is useful for contextualprocess, I'll look into that.
